import macroeconomic_theory_monetary_models_models_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace macroeconomic_theory_monetary_models_models_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end macroeconomic_theory_monetary_models_models_theorem_canonical_lane_mathlib
end HautevilleHouse
